---

atnsjoen:
  config_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment     # where to find other config files
  #config_dir: atnsjoen_catchment
  data_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment/data       # where to find data files
  repository:
    class: shyft.orchestration2.generic.Config
    params:         # add your own params here to initialize repository
  region_config_file: region.yaml
  model_config_file: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment/model_cal.yaml
  datasets_config_file: datasets.yaml
  start_datetime: 2005-07-01T00:00:00
  run_time_step: 86400
  number_of_steps: 2557 # 7 years
  #max_cells: 4  # consider only a maximum of cells (optional, mainly for testing purposes)
  #output:
  #  class: shyft.orchestration2.netcdf.SimulationOutput
  #  file: /tmp/output.nc
  #  params:
  #    - total_discharge
  #    - discharge
  #    - snow_storage
  #    - temperature
  #    - precipitation
  #state_output:
  #  params:
  #    default_flow_style: False
  #  file: state.yaml

...
