---
atnsjoen:
  config_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment     # where to find other config files
  data_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment/data       # where to find data files
  repository:
    class: shyft.orchestration2.generic.Config
    params:         # add your own params here to initialize repository
  region_config_file: region.yaml
  model_config_file: model_calibrated.yaml
  datasets_config_file: datasets.yaml
  start_datetime: 2005-07-01T00:00:00
  run_time_step: 86400
  number_of_steps: 2557 # 7 years

atnsjoen_period1:
  config_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment     # where to find other config files
  data_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment/data       # where to find data files
  repository:
    class: shyft.orchestration2.generic.Config
    params:         # add your own params here to initialize repository
  region_config_file: region.yaml
  model_config_file: model_calibrated_period1.yaml
  datasets_config_file: datasets.yaml
  start_datetime: 2005-07-01T00:00:00
  run_time_step: 86400
  number_of_steps: 2557 # 7 years

atnsjoen_period2:
  config_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment     # where to find other config files
  data_dir: /home/hub-felixmatt/shyft-course_day2/atnsjoen_catchment/data       # where to find data files
  repository:
    class: shyft.orchestration2.generic.Config
    params:         # add your own params here to initialize repository
  region_config_file: region.yaml
  model_config_file: model_calibrated_period2.yaml
  datasets_config_file: datasets.yaml
  start_datetime: 2005-07-01T00:00:00
  run_time_step: 86400
  number_of_steps: 2557 # 7 years

...
